import { AssignmentCardData } from "@/types/assignment";

export const MOCK_ASSIGNMENTS: AssignmentCardData[] = [
  {
    id: "1",
    paperId: "cbse-grade-8-science",
    title: "Quiz on Electricity",
    assignedDate: "Oct 24, 2023",
    dueDate: "Oct 31, 2023",
    status: "completed",
    totalQuestions: 15,
    totalMarks: 30,
  },
  {
    id: "2",
    paperId: "algebra-revision-test",
    title: "Algebra Revision Test",
    assignedDate: "Oct 25, 2023",
    dueDate: "Nov 02, 2023",
    status: "completed",
    totalQuestions: 20,
    totalMarks: 50,
  },
  {
    id: "3",
    paperId: "science-mid-term-assessment",
    title: "Science Mid-Term Assessment",
    assignedDate: "Oct 26, 2023",
    dueDate: "Nov 10, 2023",
    status: "completed",
    totalQuestions: 40,
    totalMarks: 100,
  },
  {
    id: "4",
    paperId: "english-grammar-worksheet",
    title: "English Grammar Worksheet",
    assignedDate: "Oct 27, 2023",
    dueDate: "Oct 30, 2023",
    status: "draft",
    totalQuestions: 10,
    totalMarks: 20,
  },
  {
    id: "5",
    paperId: "chemical-reactions-quiz",
    title: "Chemical Reactions Quiz",
    assignedDate: "Oct 28, 2023",
    dueDate: "Nov 05, 2023",
    status: "completed",
    totalQuestions: 15,
    totalMarks: 30,
  },
  {
    id: "6",
    paperId: "world-history-french-revolution",
    title: "World History: French Revolution",
    assignedDate: "Oct 29, 2023",
    dueDate: "Nov 15, 2023",
    status: "completed",
    totalQuestions: 25,
    totalMarks: 50,
  },
  {
    id: "7",
    paperId: "geometry-fundamentals",
    title: "Geometry Fundamentals",
    assignedDate: "Oct 30, 2023",
    dueDate: "Nov 12, 2023",
    status: "draft",
    totalQuestions: 18,
    totalMarks: 40,
  },
  {
    id: "8",
    paperId: "cell-biology-quiz",
    title: "Cell Biology Quiz",
    assignedDate: "Oct 31, 2023",
    dueDate: "Nov 07, 2023",
    status: "completed",
    totalQuestions: 12,
    totalMarks: 25,
  },
];
